server:
  port: 8761

spring:
  application:
    name: futur

# Eureka Libray가 포함된채로 서버가 기동이되면 Eureka Client로써 어딘가에 등록하는 작업을 수행하게됩니다.
# 여기서 true로 지정하게 되면 자신의 정보를 자신한테 등록하는 것이므로 의미가 없는 작업이므로 false로 지정 하였습니다.
eureka:
  client:
    register-with-eureka: false #eureka server를 registry에 등록할지 여부
    fetch-registry: false       #registry에 있는 정보들을 가져올지 여부
